### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by rupertford**
All lines are now covered by pytest tests. A fair few of these xfail due to the error checking being minimal at this point. I have created a new issue #18 to fix the xfail'ing tests.

### CODE REVIEW

**Comment by rupertford** [comment]
Coverage is 100%. pep8 and pyflakes give no errors. pylint is mostly OK. Ready for review.

**Review by jimboid — APPROVED** [review]
Looks OK to me, you mentioned in your comment that you are aware of the cases where testing is weak and thus opened another ticket to cover this.

On a lighter note, that case of adding "wife" to the test case "fixed", the code reads brilliantly. Made me chuckle!

Also out of curiosity, what is that coveralls bot commenting about? I haven't come across that before, is it merely commenting to link the test to the PR? I can't tell if it's message is somehow garbled.

**Comment by rupertford** [comment]
I think the coveralls bot is trying to see if there is improvement in coverage on the branch compared to the master. However, there are no tests on the master so it falls over. I seem to remember seeing the same think on another repository when I first added tests. Once this branch is on master I think (hope) all should be OK.

**Comment by rupertford** [comment]
Passed review so merging with master

**Pull request merged**
