### PR TITLE
Create .landscape.yml to increase strictness of checks

### PR DESCRIPTION
**Pull request by rupertford**
#15 proposed increasing the strictness of landscape checks. I have done this here. Note, I've ignored tests and doc strings for time being. I might revisit this in the future.

### CODE REVIEW

**Comment by rupertford** [comment]
I'm not yet sure what landscape will do with the changes as the last two melody changes are sat in a queue waiting for analysis according to landscape.io. I won't assign this to anyone until these complete.

**Comment by jimboid** [comment]
I've taken the gromacs example up to 100% (on landscape that is) on the longbow branch so you can ignore those for now, it'll go up when I eventually merge.

**Comment by jimboid** [comment]
I'll back merge this into the longbow branch once it is on master, and see if notching up the strictness has brought anything new to light.

**Comment by rupertford** [comment]
landscape failing is expected as we have increased the strictness of the checks and I have set landscape to fail if the code quality decreases.

**Review by jimboid — APPROVED** [review]
Straight forward stuff this one. 

As expected landscape is more pernickety on the stricter setting.

Not sure I agree with landscape about the too few public methods in a class (I'm not going to rant about forcing certain coding paradigms at the expense of others) but the other comments about white space are fairly trivial to fix.

I'm not going to request the change but certainly you should fix those white spaces either on this or on your next ticket.

**Comment by rupertford** [comment]
Agreed about the white spaces. My local version of pep8 didn't pick these up. I am upgrading now :-). I will fix the white spaces along with the next ticket - I don't think they warrant their own!

**Pull request merged**
